# Generated by Django 5.0.7 on 2024-07-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_timeline', to='api.project')),
            ],
        ),
    ]
