# Generated by Django 5.0.7 on 2024-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='created', max_length=10),
        ),
    ]
