# Generated by Django 5.0.7 on 2024-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_timeline_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='created', max_length=10, verbose_name='Event Type'),
        ),
    ]
