# Generated by Django 5.0.7 on 2024-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(max_length=128, verbose_name='Confirm Password'),
        ),
    ]
